version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle_lint_test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.3.8
      rails_version:
        type: string
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - samvera/cached_checkout
      - checkout

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: 'active-triples'

      # The updates need to be addressed for bixby/rubocop before this can be enabled
      # https://github.com/samvera-labs/ActiveTriples/issues/4
      # - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      # Rails 5.2
      - bundle_lint_test:
          name: ruby3-0_rails5-2
          ruby_version: 3.0.3
          rails_version: 5.2.4
      - bundle_lint_test:
          name: ruby2-7_rails5-2
          ruby_version: 2.7.5
          rails_version: 5.2.4
      - bundle_lint_test:
          name: ruby2-6_rails5-2
          ruby_version: 2.6.9
          rails_version: 5.2.4
      # Rails 6.0
      - bundle_lint_test:
          name: ruby3-0_rails6-0
          ruby_version: 3.0.3
          rails_version: 6.0.2
      - bundle_lint_test:
          name: ruby2-7_rails6-0
          ruby_version: 2.7.5
          rails_version: 6.0.2
      - bundle_lint_test:
          name: ruby2-6_rails6-0
          ruby_version: 2.6.9
          rails_version: 6.0.2
